
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int POW = 41;
  public static final int GE = 31;
  public static final int INTEGER_CONST = 52;
  public static final int INTEGER = 10;
  public static final int SEMI = 24;
  public static final int OUT = 18;
  public static final int MINUS = 37;
  public static final int WRITE = 44;
  public static final int WRITET = 47;
  public static final int NOT = 35;
  public static final int AND = 33;
  public static final int LT = 26;
  public static final int RPAR = 22;
  public static final int FUN = 14;
  public static final int OR = 34;
  public static final int BOOL = 13;
  public static final int COMMA = 23;
  public static final int DQ_STRING = 48;
  public static final int DIV = 40;
  public static final int PLUS = 36;
  public static final int LOOP = 9;
  public static final int WRITELN = 45;
  public static final int ASSIGN = 32;
  public static final int MAIN = 2;
  public static final int IF = 5;
  public static final int ID = 3;
  public static final int LE = 27;
  public static final int WRITEB = 46;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int error = 1;
  public static final int NULL = 19;
  public static final int DIVINT = 39;
  public static final int EQ = 28;
  public static final int ERROR = 50;
  public static final int MAPSUM = 20;
  public static final int REAL = 11;
  public static final int OUTPAR = 17;
  public static final int TIMES = 38;
  public static final int COLON = 25;
  public static final int ELSE = 7;
  public static final int READ = 43;
  public static final int WHILE = 8;
  public static final int SQ_STRING = 49;
  public static final int STR_CONCAT = 42;
  public static final int REAL_CONST = 54;
  public static final int THEN = 6;
  public static final int NE = 29;
  public static final int END = 15;
  public static final int BOOL_CONST = 53;
  public static final int LPAR = 21;
  public static final int STRING = 12;
  public static final int STRING_CONST = 51;
  public static final int GT = 30;
  public static final int VAR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "ID",
  "VAR",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "LOOP",
  "INTEGER",
  "REAL",
  "STRING",
  "BOOL",
  "FUN",
  "END",
  "RETURN",
  "OUTPAR",
  "OUT",
  "NULL",
  "MAPSUM",
  "LPAR",
  "RPAR",
  "COMMA",
  "SEMI",
  "COLON",
  "LT",
  "LE",
  "EQ",
  "NE",
  "GT",
  "GE",
  "ASSIGN",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVINT",
  "DIV",
  "POW",
  "STR_CONCAT",
  "READ",
  "WRITE",
  "WRITELN",
  "WRITEB",
  "WRITET",
  "DQ_STRING",
  "SQ_STRING",
  "ERROR",
  "STRING_CONST",
  "INTEGER_CONST",
  "BOOL_CONST",
  "REAL_CONST"
  };
}

